# Generated by Django 5.2 on 2025-05-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Křestní jméno')),
                ('second_name', models.CharField(max_length=50, verbose_name='Příjmení')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
    ]
