# Generated by Django 5.2 on 2025-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_premiant',
            field=models.BooleanField(default=False),
        ),
    ]
