# Generated by Django 5.2 on 2025-05-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_is_premiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_premiant',
            field=models.BooleanField(default=True),
        ),
    ]
