# Generated by Django 5.2 on 2025-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Název písně')),
                ('length', models.FloatField(verbose_name='Délka (min)')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('description', models.TextField(verbose_name='Popis')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('is_popular', models.BooleanField(verbose_name='Popularita')),
            ],
        ),
    ]
